Ext.define('app.store.DefectStore', {
	extend : 'Ext.data.Store',
        storeId: 'defectstore',
//	model : 'app.model.ChartModel',
    fields: ['defect_id','module','component','subject','description','tenant_nm','user_nm','created_by','modified_by','tenant_id','user_id','attachments','comments',
			             {
				name : 'created_dt',
				type : 'date',
				dateFormat : 'Y-m-d H:i:s T',
				convert : function(value, record) {
					value = value.toString();
//					console.log(valueindexOf(":"));
//					console.log(!isNaN(value));
					//CHECK THE VALUE IS IS IN MILLIESECONDS
					if(!isNaN(value)){
						var d = new Date(parseInt(value * 1000));
						var dt = Ext.util.Format.date(d, 'Y-m-d H:i:s T');
						return d;
					}else{
						var d = new Date(value);
						if(!isNaN(d.getTime())){
							return Ext.util.Format.date(value, 'Y-m-d H:i:s T')
						}else{
							return value;
						}
					}
					
				},
			},
//             'created_dt',
//             'modified_dt',
					{
						name : 'modified_dt',
						type : 'date',
						dateFormat : 'Y-m-d H:i:s T',
						convert : function(value, record) {
//							if(v){
//								var d = new Date(parseInt(v * 1000));
//								var dt = Ext.util.Format.date(d, 'Y-m-d H:i:s T');
//								return d;
//							}
							value = value.toString();
							//CHECK THE VALUE IS IS IN MILLIESECONDS
							if(!isNaN(value)){
								var d = new Date(parseInt(value * 1000));
								var dt = Ext.util.Format.date(d, 'Y-m-d H:i:s T');
								return d;
							}else{
								var d = new Date(value);
								if(!isNaN(d.getTime())){
									return Ext.util.Format.date(value, 'Y-m-d H:i:s T')
								}else{
									return value;
								}
							}
						},
					},
//					'deliver_dt',
					{
						name : 'deliver_dt',
						type : 'date',
						dateFormat : 'Y-m-d H:i:s T',
						convert : function(value, record) {
//							if(v){
//								var d = new Date(parseInt(v * 1000));
//								var dt = Ext.util.Format.date(d, 'Y-m-d H:i:s T');
//								return d;
//							}
							
							if(value != null){
								value = value.toString();
								//CHECK THE VALUE IS IS IN MILLIESECONDS
								if(!isNaN(value)){
//									console.log('!!!!!!!!!!!!!');
//									console.log(value);
									var d = new Date(parseInt(value * 1000));
									var dt = Ext.util.Format.date(d, 'Y-m-d H:i:s T');
									return d;
								}else{
//									console.log('11111111111111111111');
									var d = new Date(value);
									if(!isNaN(d.getTime())){
//										console.log('22222222222222222');
										return Ext.util.Format.date(value, 'Y-m-d H:i:s T')
									}else{
//										console.log('33333333333333333');
										return value;
									}
								}
							}
						},
					},
					'submitted_dt','status'],
	autoLoad : 'true',
	proxy : {
		type : 'ajax',
		method : 'POST',
		url : 'report',
		// url: 'app/data/SystemDetails.json',
		reader : {
			type : 'json',
			root : 'sysDetails'
		}
	},
	data : [
	        {
	            "defect_id": 1000,
	            "module": "Home",
	            "component": "Asset Summery",
	            "subject": "Defect In Home",
	            "description": "Asset Summery Showing wrong datas",
	            "tenant_nm": "sp_tenant",
	            "user_nm": "sp112099",
	            "created_by": null,
	            "modified_by": null,
	            "tenant_id": 2,
	            "user_id": 2,
	            "created_dt": 1488955445,
	            "modified_dt": 1488955445,
	            "deliver_dt": null,
	            "submitted_dt": 1488955445,
	            "status": "OPEN"
	        },
	        {
	            "defect_id": 1001,
	            "module": "Home",
	            "component": "Asset Summery",
	            "subject": "Defect In Home",
	            "description": "Asset Summery Showing wrong datas",
	            "tenant_nm": "sp_tenant",
	            "user_nm": "sp112099",
	            "created_by": null,
	            "modified_by": null,
	            "tenant_id": 2,
	            "user_id": 2,
	            "created_dt": 1488957401,
	            "modified_dt": 1488957401,
	            "deliver_dt": null,
	            "submitted_dt": 1488957401,
	            "status": "OPEN"
	        },
	        {
	            "defect_id": 1002,
	            "module": "Home",
	            "component": "Asset Summery",
	            "subject": "Defect In Home",
	            "description": "Asset Summery Showing wrong datas",
	            "tenant_nm": "sp_tenant",
	            "user_nm": "sp112099",
	            "created_by": null,
	            "modified_by": null,
	            "tenant_id": 2,
	            "user_id": 2,
	            "created_dt": 1488957409,
	            "modified_dt": 1488957409,
	            "deliver_dt": null,
	            "submitted_dt": 1488957409,
	            "status": "OPEN"
	        },
	        {
	            "defect_id": 1003,
	            "module": "Home",
	            "component": "Asset Summery",
	            "subject": "Defect In Home",
	            "description": "Asset Summery Showing wrong datas",
	            "tenant_nm": "sp_tenant",
	            "user_nm": "sp112099",
	            "created_by": null,
	            "modified_by": null,
	            "tenant_id": 2,
	            "user_id": 2,
	            "created_dt": 1488960116,
	            "modified_dt": 1488960116,
	            "deliver_dt": null,
	            "submitted_dt": 1488960116,
	            "status": "OPEN"
	        },
	        {
	            "defect_id": 1004,
	            "module": "Home",
	            "component": "Asset Summery",
	            "subject": "Defect In Home",
	            "description": "Asset Summery Showing wrong datas",
	            "tenant_nm": "sp_tenant",
	            "user_nm": "sp112099",
	            "created_by": null,
	            "modified_by": null,
	            "tenant_id": 2,
	            "user_id": 2,
	            "created_dt": 1488960708,
	            "modified_dt": 1488960708,
	            "deliver_dt": null,
	            "submitted_dt": 1488960708,
	            "status": "OPEN"
	        },
//	        {
//	            "defect_id": 1005,
//	            "module": "Home",
//	            "component": "Asset Summery",
//	            "subject": "Defect In Home",
//	            "description": "Asset Summery Showing wrong datas",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1488960761,
//	            "modified_dt": 1488960761,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488960761,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1006,
//	            "module": "Home",
//	            "component": "Asset Summery",
//	            "subject": "Defect In Home",
//	            "description": "Asset Summery Showing wrong datas",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1488961033,
//	            "modified_dt": 1488961033,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488961033,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1007,
//	            "module": "map",
//	            "component": "fence",
//	            "subject": "HDRDTRTRHFF",
//	            "description": "hdhdhdhhddhdhhfhf fgfhffghf fgjfg",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1488961851,
//	            "modified_dt": 1488961851,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488961851,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1008,
//	            "module": "reports",
//	            "component": "monthlySummaryReport",
//	            "subject": "Report Title",
//	            "description": "Samp Description",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488962273,
//	            "modified_dt": 1488962273,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488962273,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1009,
//	            "module": "Reports",
//	            "component": "Vehicle Monthly Report",
//	            "subject": "ZXCVZXCV",
//	            "description": "ZCVSAFWQWEDFGSBSFGS SDFSFGSFG SGSDFGSFG SSDDFG SDFGSDFG SFFSG",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488962703,
//	            "modified_dt": 1488962703,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488962703,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1010,
//	            "module": "Home",
//	            "component": "Asset Daily Summary",
//	            "subject": "Title after added feature on response",
//	            "description": "Description for Title after added feature on response ",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488965654,
//	            "modified_dt": 1488965654,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488965654,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1011,
//	            "module": "Home",
//	            "component": "Daily Event Summary",
//	            "subject": "Title after added feature on response ",
//	            "description": "Description for Title after added feature on response ",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488965708,
//	            "modified_dt": 1488965708,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488965708,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1012,
//	            "module": "Home",
//	            "component": "Asset Daily Summary",
//	            "subject": "Title after added feature on response ",
//	            "description": "Description for Title after added feature on response ",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488965855,
//	            "modified_dt": 1488965855,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488965855,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1013,
//	            "module": "Reports",
//	            "component": "Vehicle Report Card",
//	            "subject": "Title after added feature on response ",
//	            "description": "Description for Title after added feature on response ",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488965917,
//	            "modified_dt": 1488965917,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488965917,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1014,
//	            "module": "Map",
//	            "component": "POI",
//	            "subject": "asdf",
//	            "description": "adfa",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488966913,
//	            "modified_dt": 1488966913,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488966913,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1015,
//	            "module": "Map",
//	            "component": "Fence",
//	            "subject": "asdfasdfa",
//	            "description": " afadfas adfasdf adfadf aa",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488967078,
//	            "modified_dt": 1488967078,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488967078,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1016,
//	            "module": "Reports",
//	            "component": "Daily Summary Report",
//	            "subject": "sdfsdf",
//	            "description": "sfsdfawe",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488967446,
//	            "modified_dt": 1488967446,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488967446,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1017,
//	            "module": "Reports",
//	            "component": "Complete Track Report",
//	            "subject": "asdfasdfqwer",
//	            "description": "mgjghjk",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488967674,
//	            "modified_dt": 1488967674,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488967674,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1018,
//	            "module": "Map",
//	            "component": "Asset",
//	            "subject": "dafsdf",
//	            "description": "adfasdfa",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488968541,
//	            "modified_dt": 1488968541,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488968541,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1019,
//	            "module": "Map",
//	            "component": "Asset",
//	            "subject": "asdf",
//	            "description": "adfadf",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488968643,
//	            "modified_dt": 1488968643,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488968643,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1020,
//	            "module": "Reports",
//	            "component": "Usage Report Card",
//	            "subject": "asdfsdf",
//	            "description": "sdfs",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488968797,
//	            "modified_dt": 1488968797,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488968797,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1021,
//	            "module": "Reports",
//	            "component": "Complete Track Report",
//	            "subject": "asdf",
//	            "description": "adfasdf",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488968942,
//	            "modified_dt": 1488968942,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488968942,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1022,
//	            "module": "Map",
//	            "component": "POI",
//	            "subject": "adfa",
//	            "description": "asdfa asdfad adadf",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488969324,
//	            "modified_dt": 1488969324,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488969324,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1023,
//	            "module": "Map",
//	            "component": "POI",
//	            "subject": "asdfa",
//	            "description": "adsfaqrwerq",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488969552,
//	            "modified_dt": 1488969552,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488969552,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1024,
//	            "module": "Map",
//	            "component": "POI",
//	            "subject": "asdf",
//	            "description": "sdf",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488969791,
//	            "modified_dt": 1488969791,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488969791,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1025,
//	            "module": "Reports",
//	            "component": "Daily Summary Report",
//	            "subject": "New Update",
//	            "description": "Desc",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488976807,
//	            "modified_dt": 1488976807,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488976807,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1026,
//	            "module": "Map",
//	            "component": "POI",
//	            "subject": "ad",
//	            "description": "fd",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488977608,
//	            "modified_dt": 1488977608,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488977608,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1027,
//	            "module": "Home",
//	            "component": "Asset Utilization Summary",
//	            "subject": "svn",
//	            "description": "ssdfsdfa",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488977720,
//	            "modified_dt": 1488977720,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488977720,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1028,
//	            "module": "Reports",
//	            "component": "Violation Report",
//	            "subject": "Submittet On 6:59 PM",
//	            "description": "Defect Descriptiomn",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488979793,
//	            "modified_dt": 1488979793,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488979793,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1029,
//	            "module": "Home",
//	            "component": "Asset Daily Summary",
//	            "subject": "as",
//	            "description": "asdsds",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1488981449,
//	            "modified_dt": 1488981449,
//	            "deliver_dt": null,
//	            "submitted_dt": 1488981449,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1030,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "Saravanan",
//	            "description": "Perumal",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489235643,
//	            "modified_dt": 1489235643,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489235643,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1031,
//	            "module": "reports",
//	            "component": "geoFenceReport",
//	            "subject": "FIREST UPLOAD WITH IMAGES",
//	            "description": "This is the First Upload Progress directly from the Client",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489239982,
//	            "modified_dt": 1489239982,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489239982,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1032,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "SOME SUBJECT",
//	            "description": "Direct req from client with files",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489240698,
//	            "modified_dt": 1489240698,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489240698,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1033,
//	            "module": "home",
//	            "component": "assetDailySummary",
//	            "subject": "SUBJECT FINAL",
//	            "description": "Solution Identified",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489244600,
//	            "modified_dt": 1489244600,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489244600,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1034,
//	            "module": "reports",
//	            "component": "shiftTimingReport",
//	            "subject": "ONLY TWO IMAGES",
//	            "description": "Two Images Only Attached",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489244696,
//	            "modified_dt": 1489244696,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489244696,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1035,
//	            "module": "home",
//	            "component": "others",
//	            "subject": "RETURN",
//	            "description": "Test for returning data from controller to view",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489383821,
//	            "modified_dt": 1489383821,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489383821,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1036,
//	            "module": "home",
//	            "component": "others",
//	            "subject": "RETURN",
//	            "description": "Test for returning data from controller to view",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489383995,
//	            "modified_dt": 1489383995,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489383995,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1037,
//	            "module": "Home",
//	            "component": "poi",
//	            "subject": "adfad",
//	            "description": "adfadfa",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489385100,
//	            "modified_dt": 1489385100,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489385100,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1038,
//	            "module": "map",
//	            "component": "asset",
//	            "subject": "asdfasdf",
//	            "description": "sdfad",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489387750,
//	            "modified_dt": 1489387750,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489387750,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1039,
//	            "module": "map",
//	            "component": "asset",
//	            "subject": "adf",
//	            "description": "adadf",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489387884,
//	            "modified_dt": 1489387884,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489387884,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1040,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "adsf",
//	            "description": "adfadfa",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489387958,
//	            "modified_dt": 1489387958,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489387958,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1041,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "asdfa",
//	            "description": "adfadfa",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489388191,
//	            "modified_dt": 1489388191,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489388191,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1042,
//	            "module": "home",
//	            "component": "assetDailySummary",
//	            "subject": "asdasd",
//	            "description": "asdas",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489390376,
//	            "modified_dt": 1489390376,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489390376,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1043,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "sdas",
//	            "description": "sdasd",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489390478,
//	            "modified_dt": 1489390478,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489390478,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1044,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "SaraVanaN",
//	            "description": "Desc",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489390533,
//	            "modified_dt": 1489390533,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489390533,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1045,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "asdfadf",
//	            "description": "adfadf",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489399697,
//	            "modified_dt": 1489399697,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489399697,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1046,
//	            "module": "map",
//	            "component": "poi",
//	            "subject": "sdfs",
//	            "description": "sdfdfww",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489399763,
//	            "modified_dt": 1489399763,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489399763,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1047,
//	            "module": "map",
//	            "component": "fence",
//	            "subject": "adsf",
//	            "description": "adfas",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489400359,
//	            "modified_dt": 1489400359,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489400359,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1048,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "sadssdas",
//	            "description": "asdasd",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489400442,
//	            "modified_dt": 1489400442,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489400442,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1049,
//	            "module": "home",
//	            "component": "dailyEventSummary",
//	            "subject": "asdfsdf",
//	            "description": "dadfa",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489400481,
//	            "modified_dt": 1489400481,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489400481,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1050,
//	            "module": "map",
//	            "component": "fence",
//	            "subject": "adasd",
//	            "description": "sadas",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489400646,
//	            "modified_dt": 1489400646,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489400646,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1051,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "SDF",
//	            "description": "SDF",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489400687,
//	            "modified_dt": 1489400687,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489400687,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1052,
//	            "module": "reports",
//	            "component": "usageReportCard",
//	            "subject": "5 Files",
//	            "description": "Problem With 5 Attachments.",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489400758,
//	            "modified_dt": 1489400758,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489400758,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1053,
//	            "module": "map",
//	            "component": "fence",
//	            "subject": "asdf",
//	            "description": "dfasdfadf",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489401433,
//	            "modified_dt": 1489401433,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489401433,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1054,
//	            "module": "reports",
//	            "component": "completeTrackReport",
//	            "subject": "SaraVanaN",
//	            "description": "DESC",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489412025,
//	            "modified_dt": 1489412025,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489412025,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1055,
//	            "module": "reports",
//	            "component": "monthlySummaryReport",
//	            "subject": "SUBJECT",
//	            "description": "DESCRIPTION",
//	            "tenant_nm": "cuecent_tenant",
//	            "user_nm": "superadmin",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 1,
//	            "user_id": 1,
//	            "created_dt": 1489474426,
//	            "modified_dt": 1489474426,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489474426,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1056,
//	            "module": "map",
//	            "component": "poi",
//	            "subject": "SUBJECT",
//	            "description": "DESC",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489487743,
//	            "modified_dt": 1489487743,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489487743,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1057,
//	            "module": "map",
//	            "component": "asset",
//	            "subject": "asda",
//	            "description": "asdasd",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489489609,
//	            "modified_dt": 1489489609,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489489609,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1058,
//	            "module": "map",
//	            "component": "asset",
//	            "subject": "File Added Or Not",
//	            "description": "adfadfasdfsdf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489491396,
//	            "modified_dt": 1489491396,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489491396,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1059,
//	            "module": "Custom",
//	            "component": "Custom",
//	            "subject": "sfg",
//	            "description": "ssdfgsf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489491507,
//	            "modified_dt": 1489491507,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489491507,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1060,
//	            "module": "home",
//	            "component": "dailyEventSummary",
//	            "subject": "asdfa",
//	            "description": "adfa",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489492101,
//	            "modified_dt": 1489492101,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489492101,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1061,
//	            "module": "reports",
//	            "component": "fgh",
//	            "subject": "hgfh",
//	            "description": "fghfgh",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489552239,
//	            "modified_dt": 1489552239,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489552239,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1062,
//	            "module": "reports",
//	            "component": "completeTrackReport",
//	            "subject": "asdasd",
//	            "description": "sdasdas",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489559687,
//	            "modified_dt": 1489559687,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489559687,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1063,
//	            "module": "home",
//	            "component": "sdfsdf",
//	            "subject": "ASD",
//	            "description": "sdasd",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489559883,
//	            "modified_dt": 1489559883,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489559883,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1064,
//	            "module": "home",
//	            "component": "assetDailySummary",
//	            "subject": "lkk",
//	            "description": "jkl",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489572513,
//	            "modified_dt": 1489572513,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489572513,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1065,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "asd",
//	            "description": "adf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489573933,
//	            "modified_dt": 1489573933,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489573933,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1066,
//	            "module": "map",
//	            "component": "asdf",
//	            "subject": "asdfada",
//	            "description": "adadasd",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489579047,
//	            "modified_dt": 1489579047,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489579047,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1067,
//	            "module": "map",
//	            "component": "asset",
//	            "subject": "as",
//	            "description": "asd",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489579764,
//	            "modified_dt": 1489579764,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489579764,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1068,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "asdasd",
//	            "description": "asdasd",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489579983,
//	            "modified_dt": 1489579983,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489579983,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1069,
//	            "module": "home",
//	            "component": "asdf",
//	            "subject": "asd",
//	            "description": "adf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489580454,
//	            "modified_dt": 1489580454,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489580454,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1070,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "asd",
//	            "description": "asd",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489580486,
//	            "modified_dt": 1489580486,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489580486,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1071,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "asd",
//	            "description": "adf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489580720,
//	            "modified_dt": 1489580720,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489580720,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1072,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "asd",
//	            "description": "sdf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489580898,
//	            "modified_dt": 1489580898,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489580898,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1073,
//	            "module": "zz",
//	            "component": "as",
//	            "subject": "asd",
//	            "description": "asd",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489580932,
//	            "modified_dt": 1489580932,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489580932,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1074,
//	            "module": "home",
//	            "component": "asd",
//	            "subject": "asd",
//	            "description": "asd",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489580987,
//	            "modified_dt": 1489580987,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489580987,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1075,
//	            "module": "adfad",
//	            "component": "Fencesdf",
//	            "subject": "sdf",
//	            "description": "asdf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489584684,
//	            "modified_dt": 1489584684,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489584684,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1076,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "DASD",
//	            "description": "ASds",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489644911,
//	            "modified_dt": 1489644911,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489644911,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1077,
//	            "module": "map",
//	            "component": "asset",
//	            "subject": "Text with single quots '",
//	            "description": "asdfasdf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489660640,
//	            "modified_dt": 1489660640,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489660640,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1078,
//	            "module": "sdfggh '",
//	            "component": "vzx",
//	            "subject": "zxc",
//	            "description": "zxc",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489660663,
//	            "modified_dt": 1489660663,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489660663,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1079,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "asdasd",
//	            "description": "\"defect_id\": 1075,\r\n        \"module\": \"adfad\",\r\n        \"component\": \"Fencesdf\",\r\n        \"subject\": \"sdf\",\r\n        \"description\": \"asdf\",\r\n        \"tenant_nm\": \"sp_tenant\",\r\n        \"user_nm\": \"sp112099\",\r\n        \"created_by\": null,\r\n        \"modified_by\": null,\r\n        \"tenant_id\": 2,\r\n        \"user_id\": 2,\r\n        \"created_dt\": 1489584684,\r\n        \"modified_dt\": 1489584684,\r\n        \"deliver_dt\": null,\r\n        \"submitted_dt\": 1489584684,\r\n        \"status\": \"OPEN\",",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489674435,
//	            "modified_dt": 1489674435,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489674435,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1080,
//	            "module": "home",
//	            "component": "assetUtilizationSummary",
//	            "subject": "Submitted At 2017-03-17 14:37 IST",
//	            "description": "\r\n/*LAST FEED TIME IN THE TENANT*/\r\nSELECT event_dt LastFeedTime FROM mp_esn_prcfeed WHERE txn_prc_feed_id notnull ORDER BY event_dt DESC LIMIT 1\r\n\r\n\r\n\r\n/*NON REPORTING 2, 4, 6*/\r\n\r\nselect (  SELECT count(DISTINCT(asset_id)) NonReporting_2 FROM mp_esn_prcfeed WHERE txn_prc_feed_id NOTNULL \r\n\t\t\t\t\t\t\t\t\t\t\tAND (DATEDIFF('hour',(TO_TIMESTAMP(gps_dt/1000))::TIMESTAMP, (CURRENT_TIMESTAMP)::TIMESTAMP) > 2) \r\n\t\t\t\t\t\t\t\t\t\t\tAND (DATEDIFF('hour',(TO_TIMESTAMP(gps_dt/1000))::TIMESTAMP, (CURRENT_TIMESTAMP)::TIMESTAMP) <= 4)\r\n),(SELECT count(DISTINCT(asset_id)) NonReporting_4 FROM mp_esn_prcfeed WHERE txn_prc_feed_id NOTNULL \r\n\t\t\t\t\t\t\t\t\t\t\tAND (DATEDIFF('hour',(TO_TIMESTAMP(gps_dt/1000))::TIMESTAMP, (CURRENT_TIMESTAMP)::TIMESTAMP) > 4) \r\n\t\t\t\t\t\t\t\t\t\t\tAND (DATEDIFF('hour',(TO_TIMESTAMP(gps_dt/1000))::TIMESTAMP, (CURRENT_TIMESTAMP)::TIMESTAMP) <= 6)\r\n),(SELECT count(DISTINCT(asset_id)) NonReporting_6 FROM mp_esn_prcfeed WHERE txn_prc_feed_id NOTNULL \r\n\t\t\t\t\t\t\t\t\t\t\tAND (DATEDIFF('hour',(TO_TIMESTAMP(gps_dt/1000))::TIMESTAMP, (CURRENT_TIMESTAMP)::TIMESTAMP) > 6) \r\n\t\t\t\t\t\t\t\t\t\t\tAND (DATEDIFF('hour',(TO_TIMESTAMP(gps_dt/1000))::TIMESTAMP, (CURRENT_TIMESTAMP)::TIMESTAMP) <= 24)\r\n)\r\n",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489741654,
//	            "modified_dt": 1489741654,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489741654,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1081,
//	            "module": "home",
//	            "component": "Asset Utilization Summary",
//	            "subject": "asdf",
//	            "description": "aadf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489742366,
//	            "modified_dt": 1489742366,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489742366,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1082,
//	            "module": "Map",
//	            "component": "asdfa",
//	            "subject": "asdf",
//	            "description": "adf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489743009,
//	            "modified_dt": 1489743009,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489743009,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1083,
//	            "module": "Re",
//	            "component": "geoFenceReport",
//	            "subject": "dfa",
//	            "description": "adsfadf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489763938,
//	            "modified_dt": 1489763938,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489763938,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1084,
//	            "module": "Custom",
//	            "component": "Fence",
//	            "subject": "Sfsdf",
//	            "description": "sdfdfSdf",
//	            "tenant_nm": "sp_tenant",
//	            "user_nm": "sp112099",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489766711,
//	            "modified_dt": 1489766711,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489766711,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1085,
//	            "module": "sdfggh '",
//	            "component": "dddd",
//	            "subject": "asdfasdfsadasdfasfasdsda",
//	            "description": "sadfasdf\r\nasdf\r\nasd\r\nf\r\nasdf\r\nasdf",
//	            "tenant_nm": "ivms_app1_dev",
//	            "user_nm": "ivms_dev1",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489771891,
//	            "modified_dt": 1489771891,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489771891,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1086,
//	            "module": "Reports",
//	            "component": "completeTrackReport",
//	            "subject": "20-03-2017",
//	            "description": "20-03-2017 Comments",
//	            "tenant_nm": "ivms_app1_dev",
//	            "user_nm": "ivms_dev1",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489987873,
//	            "modified_dt": 1489987873,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489987873,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1087,
//	            "module": "Custom",
//	            "component": "Fence",
//	            "subject": "sdad",
//	            "description": "sda",
//	            "tenant_nm": "ivms_app1_dev",
//	            "user_nm": "ivms_dev1",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489988796,
//	            "modified_dt": 1489988796,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489988796,
//	            "status": "OPEN"
//	        },
//	        {
//	            "defect_id": 1088,
//	            "module": "Re",
//	            "component": "geoFenceReport",
//	            "subject": "asd",
//	            "description": "asssssassssss\r\nsssssssss sssssssss\r\nssssssssssssssss ssssss\r\nsssssssssssssssssss ssssssss\r\nsssssssssssssssssssss sssssssssssss\r\nssssssssssssssssaaaaaaaa aaaaaaaaaaaaaa\r\naaaaaaaaaaaaaaaaaaaaaaaaaawww wwwwwwwww\r\nwwwwwwwwwwwwwwwqqqqqqqqqqqqqqqqqqqq qqqqq\r\nqqqqqqqqrrrrrrrrrrrrrrrrrrrrrrrrdddddddddddddddddddddddddddddd\r\n",
//	            "tenant_nm": "ivms_app1_dev",
//	            "user_nm": "ivms_dev1",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1489993184,
//	            "modified_dt": 1489993184,
//	            "deliver_dt": null,
//	            "submitted_dt": 1489993184,
//	            "status": "CLOSED"
//	        },
//	        {
//	            "defect_id": 1089,
//	            "module": "adfad",
//	            "component": "asd",
//	            "subject": "sdfsd",
//	            "description": "fsdfsdffd\r\nsdfsdfsdfsd\r\nsdfsdfsdfsdfsd\r\nsdfsdfsdfsdfsdfsdf\r\nsdfsdfasdfadsfadfad\r\nadsfadfadfasdfsadfasdfa\r\nadsfadfadfad\r\nasdfasdf\r\nasdfas\r\nasdfasdf\r\nasdfa\r\nasd\r\nsd\r\na",
//	            "tenant_nm": "ivms_app1_dev",
//	            "user_nm": "ivms_dev1",
//	            "created_by": null,
//	            "modified_by": null,
//	            "tenant_id": 2,
//	            "user_id": 2,
//	            "created_dt": 1490024342,
//	            "modified_dt": 1490024342,
//	            "deliver_dt": null,
//	            "submitted_dt": 1490024342,
//	            "status": "OPEN"
//	        }
	    ]
});